<?php

namespace Kore\AdminBundle\Entity;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
