<?php

namespace Kore\AdminBundle\Entity;

/**
 * EncuestadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncuestadorRepository extends \Doctrine\ORM\EntityRepository
{
}
