<?php

namespace Kore\AdminBundle\Entity;

/**
 * IssuerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuerRepository extends \Doctrine\ORM\EntityRepository
{
}
