<?php

namespace Kore\AdminBundle\Entity;

/**
 * PersonaAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
