<?php

namespace Kore\AdminBundle\Entity;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(p.id)')
            ->from('KoreAdminBundle:Persona', 'p')
        ;
        return $qb->getQuery()->getSingleScalarResult();
    }
}
