<?php

namespace Kore\AdminBundle\Entity;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCm($cm)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p.cm')
            ->from('KoreAdminBundle:Product', 'p')
            ->where('p.cm LIKE :cm')
            ->setParameter('cm', '%'.$cm.'%')
            ->setMaxResults(10)
        ;
        return $qb->getQuery()->getArrayResult();
    }

    public function findByName($name)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('p.id, p.name')
            ->from('KoreAdminBundle:Product', 'p')
            ->where('p.name LIKE :name')
            ->setParameter('name', '%'.$name.'%')
            ->setMaxResults(10)
        ;
        return $qb->getQuery()->getArrayResult();
    }
}
