<?php

namespace Kore\AdminBundle\Entity;

/**
 * RutaEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
