<?php

namespace Kore\AdminBundle\Entity;

/**
 * RutaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutaRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(r.id)')
            ->from('KoreAdminBundle:Ruta', 'r')
        ;
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function countByEstadoCodigo($codigo)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(r.id)')
            ->from('KoreAdminBundle:Ruta', 'r')
            ->join('r.estado', 're')
            ->where('re.codigo = :codigo')
            ->setParameter('codigo', $codigo);
        ;
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findByEstadoId($id, $sort = null, $direction = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('r, res, ren')
            ->from('KoreAdminBundle:Ruta', 'r')
            ->join('r.estado', 'res')
            ->join('r.encuestador', 'ren')
            ->where('res.id = :id')
            ->setParameter('id', $id);
        ;
        if($sort && $direction) $qb->orderBy('r.'.$sort, $direction);
        else $qb->orderBy('r.id', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
