<?php

namespace Kore\AdminBundle\Entity;

/**
 * SellerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SellerRepository extends \Doctrine\ORM\EntityRepository
{
}
