<?php

namespace Kore\AdminBundle\Entity;

/**
 * SolicitudAccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudAccionRepository extends \Doctrine\ORM\EntityRepository
{
}
