<?php

namespace Kore\AdminBundle\Entity;

/**
 * SolicitudTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
