<?php

namespace Kore\AdminBundle\Entity;

/**
 * SolicitudEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudEstadoRepository extends \Doctrine\ORM\EntityRepository
{
}
