kore_agent_budget:
    resource: "@KoreAgentBundle/Resources/config/routing/budget.yml"
    prefix:   /budget

kore_agent_client:
    resource: "@KoreAgentBundle/Resources/config/routing/client.yml"
    prefix:   /client

kore_agent_item:
    resource: "@KoreAgentBundle/Resources/config/routing/item.yml"
    prefix:   /item

kore_agent_product:
    resource: "@KoreAgentBundle/Resources/config/routing/product.yml"
    prefix:   /product

kore_agent_provider:
    resource: "@KoreAgentBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

kore_agent_seller:
    resource: "@KoreAgentBundle/Resources/config/routing/seller.yml"
    prefix:   /seller

kore_agent_note:
    resource: "@KoreAgentBundle/Resources/config/routing/note.yml"
    prefix:   /note

kore_agent_search:
    resource: "@KoreAgentBundle/Resources/config/routing/search.yml"
    prefix:   /search

kore_agent:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: agent_budget_index
        permanent: true