services:
#    validator.existe_rut:
#        class: Kore\AgentBundle\Validator\Constraints\ExisteRutValidator
#        arguments: [@doctrine.orm.entity_manager]
#        tags:
#            - { name: validator.constraint_validator, alias: existe_rut }
#    kore_agent.example:
#        class: Kore\AgentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
