services:
    kore_agent.form.item:
        class: Kore\AgentBundle\Form\ItemType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: kore_agentbundle_item }
