agent_client_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:Client:index" }
    methods:  GET

agent_client_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:Client:show" }
    methods:  GET

agent_client_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:Client:new" }
    methods:  [GET, POST]

agent_client_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:Client:edit" }
    methods:  [GET, POST]

agent_client_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:Client:delete" }
    methods:  DELETE
