agent_note_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:Note:index" }
    methods:  GET

agent_note_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:Note:show" }
    methods:  GET

agent_note_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:Note:new" }
    methods:  [GET, POST]

agent_note_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:Note:edit" }
    methods:  [GET, POST]

agent_note_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:Note:delete" }
    methods:  DELETE
