agent_personaaccion_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:PersonaAccion:index" }
    methods:  GET

agent_personaaccion_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:PersonaAccion:show" }
    methods:  GET

agent_personaaccion_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:PersonaAccion:new" }
    methods:  [GET, POST]

agent_personaaccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:PersonaAccion:edit" }
    methods:  [GET, POST]

agent_personaaccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:PersonaAccion:delete" }
    methods:  DELETE
