agent_provider_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:Provider:index" }
    methods:  GET

agent_provider_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:Provider:show" }
    methods:  GET

agent_provider_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:Provider:new" }
    methods:  [GET, POST]

agent_provider_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:Provider:edit" }
    methods:  [GET, POST]

agent_provider_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:Provider:delete" }
    methods:  DELETE
