agent_ruta_estado_0:
    path:     /estado0
    defaults: { _controller: "KoreAgentBundle:Ruta:index", codigo: 'R00' }
    methods:  GET

agent_ruta_estado_5:
    path:     /estado5
    defaults: { _controller: "KoreAgentBundle:Ruta:index", codigo: 'R05' }
    methods:  GET

agent_ruta_estado_10:
    path:     /estado10
    defaults: { _controller: "KoreAgentBundle:Ruta:index", codigo: 'R10' }
    methods:  GET

agent_ruta_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:Ruta:show" }
    methods:  GET

agent_ruta_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "KoreAgentBundle:Ruta:pdf" }
    methods:  GET

agent_ruta_export:
    path:     /{id}/export
    defaults: { _controller: "KoreAgentBundle:Ruta:export" }
    methods:  GET

agent_ruta_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:Ruta:new" }
    methods:  [GET, POST]

agent_ruta_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:Ruta:edit" }
    methods:  [GET, POST]

agent_ruta_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:Ruta:delete" }
    methods:  DELETE

agent_ruta_receipt:
    path:     /{id}/receipt
    defaults: { _controller: "KoreAgentBundle:Ruta:receipt" }
    methods:  [GET, POST]

agent_ruta_buscar:
    path:     /buscar
    defaults: { _controller: "KoreAgentBundle:Ruta:buscar" }
    methods:  [GET, POST]
