agent_rutaestado_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:RutaEstado:index" }
    methods:  GET

agent_rutaestado_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:RutaEstado:show" }
    methods:  GET

agent_rutaestado_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:RutaEstado:new" }
    methods:  [GET, POST]

agent_rutaestado_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:RutaEstado:edit" }
    methods:  [GET, POST]

agent_rutaestado_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:RutaEstado:delete" }
    methods:  DELETE
