agent_seller_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:Seller:index" }
    methods:  GET

agent_seller_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:Seller:show" }
    methods:  GET

agent_seller_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:Seller:new" }
    methods:  [GET, POST]

agent_seller_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:Seller:edit" }
    methods:  [GET, POST]

agent_seller_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:Seller:delete" }
    methods:  DELETE
