agent_solicitudaccion_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:SolicitudAccion:index" }
    methods:  GET

agent_solicitudaccion_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:SolicitudAccion:show" }
    methods:  GET

agent_solicitudaccion_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:SolicitudAccion:new" }
    methods:  [GET, POST]

agent_solicitudaccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:SolicitudAccion:edit" }
    methods:  [GET, POST]

agent_solicitudaccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:SolicitudAccion:delete" }
    methods:  DELETE
