agent_solicitudestado_index:
    path:     /
    defaults: { _controller: "KoreAgentBundle:SolicitudEstado:index" }
    methods:  GET

agent_solicitudestado_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAgentBundle:SolicitudEstado:show" }
    methods:  GET

agent_solicitudestado_new:
    path:     /new
    defaults: { _controller: "KoreAgentBundle:SolicitudEstado:new" }
    methods:  [GET, POST]

agent_solicitudestado_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAgentBundle:SolicitudEstado:edit" }
    methods:  [GET, POST]

agent_solicitudestado_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAgentBundle:SolicitudEstado:delete" }
    methods:  DELETE
