knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:
            orientation: Portrait
            page-size: Letter
            viewport-size: 1280x768
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:    []