_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

kore_admin:
    resource: "@KoreAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

kore_agent:
    resource: "@KoreAgentBundle/Resources/config/routing.yml"
    prefix:   /agent

kore_user:
    resource: "@KoreUserBundle/Resources/config/routing.yml"
    prefix:   /

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: agent_root
        permanent: true

