security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
                users:
                    root: { password: %root_password%, roles: 'ROLE_USER' }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: /login
                check_path: /login
                failure_path: /login
                always_use_default_target_path: true
                default_target_path: /agent
                csrf_token_generator: security.csrf.token_manager
                failure_path: /login
            logout:
                path:   /logout
                target: /login
    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/logout, roles: [ROLE_USER] }
        - { path: ^/agent, roles: [ROLE_USER] }
