security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        Kore\AdminBundle\Entity\User: bcrypt

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    root: { password: %root_password%, roles: 'ROLE_USER' }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: fos_user_security_login 
                check_path: fos_user_security_check
                failure_path: fos_user_security_login
                always_use_default_target_path: true
                default_target_path: /agent
                csrf_token_generator: security.csrf.token_manager
                failure_path: /login
            remember_me:
                secret: '%secret%'
            logout:
                path:   /logout
                target: /login
    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/admin, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/logout, roles: [ROLE_USER] }
        - { path: ^/agent, roles: [ROLE_USER] }
