admin_domicilio_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Domicilio:index" }
    methods:  GET

admin_domicilio_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Domicilio:show" }
    methods:  GET

admin_domicilio_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Domicilio:new" }
    methods:  [GET, POST]

admin_domicilio_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Domicilio:edit" }
    methods:  [GET, POST]

admin_domicilio_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Domicilio:delete" }
    methods:  DELETE
