admin_product_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Product:index" }
    methods:  GET

admin_product_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Product:show" }
    methods:  GET

admin_product_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Product:new" }
    methods:  [GET, POST]

admin_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Product:edit" }
    methods:  [GET, POST]

admin_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Product:delete" }
    methods:  DELETE
