admin_provider_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Provider:index" }
    methods:  GET

admin_provider_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Provider:show" }
    methods:  GET

admin_provider_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Provider:new" }
    methods:  [GET, POST]

admin_provider_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Provider:edit" }
    methods:  [GET, POST]

admin_provider_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Provider:delete" }
    methods:  DELETE
