admin_ruta_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Ruta:index" }
    methods:  GET

admin_ruta_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Ruta:show" }
    methods:  GET

admin_ruta_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Ruta:new" }
    methods:  [GET, POST]

admin_ruta_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Ruta:edit" }
    methods:  [GET, POST]

admin_ruta_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Ruta:delete" }
    methods:  DELETE
