admin_solicitudestado_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:SolicitudEstado:index" }
    methods:  GET

admin_solicitudestado_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:SolicitudEstado:show" }
    methods:  GET

admin_solicitudestado_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:SolicitudEstado:new" }
    methods:  [GET, POST]

admin_solicitudestado_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:SolicitudEstado:edit" }
    methods:  [GET, POST]

admin_solicitudestado_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:SolicitudEstado:delete" }
    methods:  DELETE
