admin_solicitud_index:
    path:     /
    defaults: { _controller: "KoreAdminBundle:Solicitud:index" }
    methods:  GET

admin_solicitud_show:
    path:     /{id}/show
    defaults: { _controller: "KoreAdminBundle:Solicitud:show" }
    methods:  GET

admin_solicitud_new:
    path:     /new
    defaults: { _controller: "KoreAdminBundle:Solicitud:new" }
    methods:  [GET, POST]

admin_solicitud_edit:
    path:     /{id}/edit
    defaults: { _controller: "KoreAdminBundle:Solicitud:edit" }
    methods:  [GET, POST]

admin_solicitud_delete:
    path:     /{id}/delete
    defaults: { _controller: "KoreAdminBundle:Solicitud:delete" }
    methods:  DELETE
