Kore\AdminBundle\Entity\Client:
    type: entity
    table: Client
    repositoryClass: Kore\AdminBundle\Entity\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Kore\AdminBundle\Entity\User
            inversedBy: clients
    oneToMany:
        budgets:
            targetEntity: Kore\AdminBundle\Entity\Budget
            mappedBy: client
    fields:
        name:
            type: string
            length: 30
            nullable: true
        rut:
            type: string
            length: 30
            nullable: true
        contactname:
            type: string
            length: 30
            nullable: true
        phone:
            type: string
            length: 30
            nullable: true
        email:
            type: string
            length: 30
            nullable: true
        address:
            type: string
            length: 100
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
