Kore\AdminBundle\Entity\Group:
    type: entity
    table: kore_group
    repositoryClass: Kore\AdminBundle\Entity\GroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
        users:
            targetEntity: Kore\AdminBundle\Entity\User
            mappedBy: groups
    fields:
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
