Kore\AdminBundle\Entity\Group:
    type: entity
    table: kore_group
    repositoryClass: Kore\AdminBundle\Entity\GroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        issuers:
            targetEntity: Kore\AdminBundle\Entity\Issuer
            mappedBy: group
        providers:
            targetEntity: Kore\AdminBundle\Entity\Provider
            mappedBy: group
        sellers:
            targetEntity: Kore\AdminBundle\Entity\Seller
            mappedBy: group
        clients:
            targetEntity: Kore\AdminBundle\Entity\Client
            mappedBy: group
        budgets:
            targetEntity: Kore\AdminBundle\Entity\Budget
            mappedBy: group
        products:
            targetEntity: Kore\AdminBundle\Entity\Product
            mappedBy: group
        notes:
            targetEntity: Kore\AdminBundle\Entity\Note
            mappedBy: group
        users:
            targetEntity: Kore\AdminBundle\Entity\User
            mappedBy: group
    fields:
        name:
            type: string
            length: 100
            nullable: true
        predefined_note:
            type: text
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deleted_at:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deleted_at
            time_aware: false
    lifecycleCallbacks: {  }
