kore_admin_user:
    resource: "@KoreAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

kore_admin_budget:
    resource: "@KoreAdminBundle/Resources/config/routing/budget.yml"
    prefix:   /budget

kore_admin_client:
    resource: "@KoreAdminBundle/Resources/config/routing/client.yml"
    prefix:   /client

kore_admin_item:
    resource: "@KoreAdminBundle/Resources/config/routing/item.yml"
    prefix:   /item

kore_admin_product:
    resource: "@KoreAdminBundle/Resources/config/routing/product.yml"
    prefix:   /product

kore_admin_provider:
    resource: "@KoreAdminBundle/Resources/config/routing/provider.yml"
    prefix:   /provider

kore_admin_seller:
    resource: "@KoreAdminBundle/Resources/config/routing/seller.yml"
    prefix:   /seller

kore_admin_note:
    resource: "@KoreAdminBundle/Resources/config/routing/note.yml"
    prefix:   /note

